# 공통 설정
common:
  namespace: envoy-gateway-system

gateway:
  name: "cmp-gateway" # 기본값 (스크립트에서 덮어쓸 예정)
  tls:
    name: "strato-tls"

service:
  trafficPolicy: Cluster
  type: LoadBalancer

envoy:
  nodeName: "" # 스크립트에서 주입
  image: "docker.io/envoyproxy/envoy:distroless-v1.36.3"