apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitlab-webservice
  namespace: gitlab  # GitLab이 설치된 네임스페이스
spec:
  parentRefs:
    - name: cmp-gateway
      namespace: envoy-gateway-system # Gateway가 위치한 네임스페이스
  hostnames:
    - "gitlab.devops.internal"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gitlab-webservice-default
          port: 8181

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitlab-registry
  namespace: gitlab
spec:
  parentRefs:
    - name: cmp-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "registry.devops.internal"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gitlab-registry
          port: 5000

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitlab-minio
  namespace: gitlab
spec:
  parentRefs:
    - name: cmp-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "minio.devops.internal"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gitlab-minio-svc
          port: 9000

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitlab-kas
  namespace: gitlab
spec:
  parentRefs:
    - name: cmp-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "kas.devops.internal"
  rules:
    # 1순위: /k8s-proxy/ 경로는 8154 포트로 (WebSocket/Agent 통신)
    - matches:
        - path:
            type: PathPrefix
            value: /k8s-proxy/
      backendRefs:
        - name: gitlab-kas
          port: 8154
    # 2순위: 그 외 나머지(/)는 8150 포트로
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gitlab-kas
          port: 8150
